# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "."
    steps:
      - run:
          name: "List Directory"
          command: ls -al << parameters.path >>
  install:
    description: "Install dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install & Link Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  yarn:
    description: "Excutes yarn cmds"
    parameters:
      method:
        type: string
    steps:
      - run:
          name: yarn << parameters.method >>
          command: yarn << parameters.method >>

# Common executor for node based jobs
executors:
  node-executor:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/webpack-hot-server-middleware


# Define jobs
jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - install

      # Save project
      - persist_to_workspace:
          root: .
          paths: 
            - .

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/webpack-hot-server-middleware

      # Run test
      - run:
          name: Test source
          command: yarn test

workflows:
  version: 2.1
  runner:
    jobs:
      - setup
      - test:
          requires:
            - setup